#!/usr/bin/env python

import  sys
sys.path.append("lib")

import  HTSeq       as      ht
import  argparse
import  utils
import  annotation
import  stats
import  parse 
import  os

def parse_arguments():
    """ Parse arguments """
    parser = argparse.ArgumentParser(description='Harness and plot feature coverage statistics.')
    parser.add_argument('input_file', metavar='input file', type=str, nargs=1,default=None,
                   help='Input BAM file.')
    parser.add_argument('-g', metavar='gtf', type=str, default="", help='Annotation in GFF format.')
    parser.add_argument('-d', metavar='pickle_prefix', type=str, default="", help='Pickles directory.')
    parser.add_argument('-s', action='store_true' ,default=False, help='Stranded analysis.')
    args            = parser.parse_args()
    return args

args    = parse_arguments()
L       = utils.Log()

# Load annotation:
annot   = annotation.Annotation(args.g, args.s, L)

# Parse BAM files:
bam     = args.input_file[0]
parser  = parse.Parse(bam, annot, L)
st      = parser.parse()
# Pickle stats:
pickle_file  = os.path.join(args.d, utils.clean_name(bam) + ".pk")
utils.pickle_dump(st, pickle_file)
print st
