#!/usr/bin/env python
import      os                                                                                                                                                 
import      sys                                                                                                                                                
sys.path.append('./lib')
import      time                                                                                                                                               
import      matplotlib                                                                                                                                         
matplotlib.use('Agg')                                                                                                                                          
from        matplotlib                      import  pyplot          as  plt                                                                                    
from        collections                     import  defaultdict                                                                                                
from        collections                     import  OrderedDict                                                                                                
from        matplotlib.backends.backend_pdf import  PdfPages                                                                                                   
import      numpy                           as      np                                                                                                         
import      cPickle                                                                                                                                            
import      HTSeq                           as      ht
import      itertools                       as      it
import      argparse
from        collections                     import  namedtuple
import      re
from        matplotlib                      import  colors
import      cPickle
import      scipy.stats
